export type DailySignCopy = {
  headlines: string[];
  summaries: string[];
  advice: string[];
  avoid: string[];
  rituals: string[];
  rhythm: {
    sabah: [string, string];
    ogle: [string, string];
    aksam: [string, string];
  };
};

/** Per-sign daily language. `{name}` and `{moon}` are filled at read time. */
export const DAILY_SIGN_COPY: Record<string, DailySignCopy> = {
  koc: {
    headlines: [
      "{name}: ilk adımı sen seç",
      "{moon} altında {name} kıvılcımı",
      "Bugün {name} hızını ölçülü tut",
      "{name} için net bir başlangıç",
      "{moon} · {name} öne çıkar",
      "{name}: yönünü tek cümlede kur",
    ],
    summaries: [
      "Koç gününde enerji erken uyanır. Hızın işe yaraması için tek bir hedef yeter.",
      "İlk kıvılcım sende. Bugün her kapıyı açmak yerine bir eşiği net seç.",
      "Ateşin taze. Kararını geciktirme; ama sözünü de aceleyle büyütme.",
      "Hareket ihtiyacın yüksek. Küçük bir adım, dağınık bir günü toparlar.",
      "Cesaretin açık. Onu gösterişe değil, seçtiğin tek işe ver.",
      "Tempo sende. Başkalarının ritmine girmeden kendi başlangıcını koru.",
    ],
    advice: [
      "Tek bir işe atıl ve onu bitene kadar dağıtma.",
      "İlk sözünü kısa tut; hızın netlikle gelsin.",
      "Günü bir başlangıçla aç, üç işi birden sürme.",
      "Cesaretini göster ama kanıtlamaya çalışma.",
      "Kararını sabah ver, günü onun etrafında kur.",
      "Adımını seç, sonra tempo tut.",
    ],
    avoid: [
      "Her itirazı kişisel bir meydan okuma gibi büyütme.",
      "Aceleyle verilen söz, günün geri kalanını bağlar.",
      "Tartışmayı kazanmak için yönünü kaybetme.",
      "Bitirmeden yeni bir ateş yakma.",
      "Sert çıkışını son söz sanma.",
      "Hızını başkasının temposunu ezmek için kullanma.",
    ],
    rituals: [
      "Bir dakika dur: bugün atacağın tek adımı aklında netleştir.",
      "Nefesini üç kez yavaşlat ve ilk niyetini sessizce söyle.",
      "Gözlerini kapatıp bugünün tek başlangıcını seç.",
      "Omuzlarını bırak, sonra o ilk adımı zihninde tamamla.",
      "Kısa bir nefes halkası: acele değil, yön.",
      "Bir dakikalığına dur ve kıvılcımı tek işe bağla.",
    ],
    rhythm: {
      sabah: ["Yönünü ilk saatlerde seç; Koç günü geç açılmaz.", "Güne tek niyetle başla, hız sonra gelir."],
      ogle: ["Tartışmayı kısalt; net cümle yeter.", "Öğleden sonra yeni iş açma, seçtiğini ilerlet."],
      aksam: ["Günü kapatırken kazanılmış bir savaşı yeniden kurma.", "Akşam temposunu düşür; yarının kıvılcımı için yer aç."],
    },
  },
  boga: {
    headlines: [
      "{name}: ritmini bozma",
      "{moon} altında {name} sakin durur",
      "Bugün {name} için sağlam bir tempo",
      "{name} değerini aceleye kaptırma",
      "{moon} · {name} yavaş ve net",
      "{name}: bedeninle aynı hizada kal",
    ],
    summaries: [
      "Boğa günü acele etmez. Kalıcı olan, yavaş ve seçilmiş olandır.",
      "Güven hissin önde. Bugün ritmini bozan teklifleri nazikçe geri çevir.",
      "Toprak sende. Küçük, somut bir iş günü daha iyi taşır.",
      "Haz ve düzen aynı yerde durabilir. Aşırı yüklenme, ikisini de bozar.",
      "Sessiz gücün açık. Savunmana gerek yok; temposunu koruman yeter.",
      "Değer verdiğin şeye zaman ayır. Dağınık bir gün, Boğa’yı yorar.",
    ],
    advice: [
      "Günü sade bir plana bağla ve o plandan şaşma.",
      "Bir işi yavaş bitir; üç işi yarım bırakma.",
      "Bedeninin ritmini dinle, temposunu zorlama.",
      "Değer verdiğin bir şeye somut zaman ayır.",
      "Kararını sindirerek ver, acele pazarlığa girme.",
      "Bugünü sakin ve ölçülü tut.",
    ],
    avoid: [
      "Seni acele ettiren tekliflere hemen evet deme.",
      "Konfor adına ertelemeyi büyütme.",
      "Para, yemek veya işte fazlayı ‘hak’ gibi görme.",
      "İnatla durduğun yer aslında korku olabilir; bak.",
      "Günün ritmini başkasının acelesine teslim etme.",
      "Değişimi tehdit sanıp her kapıyı kapatma.",
    ],
    rituals: [
      "Bir dakika dur: nefesini ağırlaştır ve ayaklarını yere hisset.",
      "Omuzlarını indir, çeneni bırak, bugünün temposunu seç.",
      "Sessizce bir şey say: nefes, adım, niyet. Üçü yeter.",
      "Ellerini birleştirip bugün koruyacağın tek şeyi düşün.",
      "Yavaş bir nefes halkası: acele yok, süreklilik var.",
      "Bir dakikalığına dur ve bedeninin ritmine geri dön.",
    ],
    rhythm: {
      sabah: ["Güne acele etmeden, somut bir iş sırasıyla başla.", "Sabah ritmini koru; ilk saatleri doldurma."],
      ogle: ["Öğleden sonra pazarlığı uzatma, net bir sınır koy.", "Yemeği ve işi ayır; ikisini birden sıkıştırma."],
      aksam: ["Akşamı sakin kapat; yarını şimdiden doldurma.", "Konforu uyuşukluğa çevirmeden günü bırak."],
    },
  },
  ikizler: {
    headlines: [
      "{name}: fikrini tek cümleye indir",
      "{moon} altında {name} zihin açılır",
      "Bugün {name} için seçilmiş bir söz",
      "{name} dağılmadan konuşsun",
      "{moon} · {name} iki yolu birleştirir",
      "{name}: merakını tek kanala al",
    ],
    summaries: [
      "İkizler gününde zihin hızlıdır. Hızın işe yaraması için bir kanal seçmen gerekir.",
      "Fikirler çoğalır. Bugün hepsini paylaşmak yerine birini netleştir.",
      "Konuşma isteğin yüksek. Dinlemek, sözünü daha keskin yapar.",
      "İki yön birden çekebilir. Birini bugüne, diğerini yarına bırak.",
      "Merakın canlı. Onu dağıtmak yerine tek bir soruya bağla.",
      "Haber, mesaj, fikir… hepsi açık. Süzgeç sen ol.",
    ],
    advice: [
      "Fikrini tek net cümleye indir, sonra paylaş.",
      "Bir konuşmayı seç; beş sohbeti aynı anda açma.",
      "Merakını tek bir soruya bağla.",
      "Yazmadan önce bir nefes al, sonra gönder.",
      "İki seçenek varsa bugün birini dene.",
      "Sözünü kısalt, dinlemeyi uzat.",
    ],
    avoid: [
      "Her bildirimi cevaplamak zorunda değilsin.",
      "Yarım bilgiyle kesin konuşma.",
      "Konuyu değiştirerek kaçma; bir cümlede dur.",
      "İki işi ‘çok yönlülük’ diye aynı anda büyütme.",
      "Sözünü spekülasyonla süsleme.",
      "Başkasının fikrini kendi fikrin gibi taşıma.",
    ],
    rituals: [
      "Bir dakika dur: zihnindeki cümleleri tek niyete indir.",
      "Nefesini say ve bugün söyleyeceğin tek sözü seç.",
      "Gözlerini kapat, dağılan düşünceyi bir soruya bağla.",
      "Kısa bir sessizlik: konuşmadan önce boşluk bırak.",
      "Bir dakikalığına ekranı bırak ve nefese dön.",
      "Zihnini yavaşlat: bir cümle, bir nefes, bir yön.",
    ],
    rhythm: {
      sabah: ["Sabah mesajları ele; günü bildirimle başlatma.", "İlk saatlerde tek bir yazı veya konuşma seç."],
      ogle: ["Öğleden sonra sohbeti net tut, yan konulara kayma.", "İki toplantıyı birleştirme; araya boşluk koy."],
      aksam: ["Akşam zihnini kapat: yarının fikirleri yarına kalsın.", "Gece konuşmasını uzatma, uykuya yer aç."],
    },
  },
  yengec: {
    headlines: [
      "{name}: içini koru, kapını seç",
      "{moon} altında {name} yumuşak durur",
      "Bugün {name} için güvenli bir alan",
      "{name} hissini aceleye kaptırma",
      "{moon} · {name} evini içinde kurar",
      "{name}: bakımı öne al",
    ],
    summaries: [
      "Yengeç gününde iç dünya öne çıkar. Koruma, kaçmak değil; seçerek açılmaktır.",
      "Duygular netleşmeden söz büyümesin. Küçük bir bakım, günü taşır.",
      "Yakınlık isteğin yüksek. Herkese değil, güvendiğin yere yaklaş.",
      "Geçmiş yankılanabilir. Onu bugünün kararına çevirme.",
      "Hassasiyetin açık. Bu bir zayıflık değil; süzgeç.",
      "Yuva hissi sende. Onu mekânla, insanla veya sessizlikle kur.",
    ],
    advice: [
      "İç sesine kısa bir alan aç, sonra konuş.",
      "Bugün birini koru: kendini veya gerçekten yakın olanı.",
      "Hissini adlandırmadan karar verme.",
      "Evinde veya rutininde küçük bir bakım yap.",
      "Kapını herkese açma; birine net aç.",
      "Duyguyu yutma, ama sahneye de çevirme.",
    ],
    avoid: [
      "Alınganlığı kanıt gibi kullanma.",
      "Geçmiş bir sahneyi bugüne taşıyıp herkesi yargılama.",
      "İhtiyacını dolaylı imayla bekletme.",
      "Başkasının ruh halini kendi işin sanma.",
      "Kaçarak korunma; sınır koyarak korun.",
      "Duyguyu gizleyeyim derken içini kilitleme.",
    ],
    rituals: [
      "Bir dakika dur: elini göğsüne koy ve nefesini yumuşat.",
      "İçeride kalan cümleyi sessizce tamamla, sonra bırak.",
      "Güvende hissettiğin bir yeri zihninde kur, orada kal.",
      "Nefesini su gibi akıt: zorlama, taşı.",
      "Bir dakikalığına bakımı kendine çevir.",
      "Yumuşak bir durak: bugün kime açık olduğunu seç.",
    ],
    rhythm: {
      sabah: ["Güne yumuşak başla; ilk temasını seçerek kur.", "Sabah hissini yaz veya tut, hemen paylaşma."],
      ogle: ["Öğleden sonra yakınlık isteğini işe karıştırma.", "Duygusal bir kıpırtı varsa kısa bir mola ver."],
      aksam: ["Akşamı ev gibi kapat; günü yeniden yaşamaya çalışma.", "Geceyi koru: fazla konuşma, fazla izleme."],
    },
  },
  aslan: {
    headlines: [
      "{name}: görün ama kanıtlama",
      "{moon} altında {name} ısınır",
      "Bugün {name} için seçilmiş bir sahne",
      "{name} ışığını ölçülü tut",
      "{moon} · {name} öne çıkar, yumuşakça",
      "{name}: kalbi açık, ego sakin",
    ],
    summaries: [
      "Aslan gününde görünürlük artar. Işık işe yarar; sahne ihtiyacı yormaz.",
      "Sıcaklığın açık. Onu onay için değil, seçtiğin iş için kullan.",
      "Gurur zedelenebilir. Küçük bir övgü yeter, büyük bir ispat gerekmez.",
      "Yaratmak isteğin yüksek. Bir işi güzel bitirmek, üçünü ilan etmekten güçlü.",
      "Kalbin önde. Cömert ol, ama herkesi sahneye alma.",
      "Bugün parlamak serbest. Gölgede kalanı ezmek serbest değil.",
    ],
    advice: [
      "Bir işi görünür kıl, gerisini sessizce ilerlet.",
      "Övgüyü beklemeden seçtiğin şeyi tamamla.",
      "Sıcaklığını paylaş; sahneyi büyütme.",
      "Bugün tek bir jest yeter: net, cömert, kısa.",
      "Işığını bir kişiye veya bir işe ver.",
      "Görünür ol, kanıt sunmaya çalışma.",
    ],
    avoid: [
      "Görmezden gelinmeyi hakaret gibi büyütme.",
      "Alkış için sözünü uzatma.",
      "Başkasının ışığını kısarak parlama.",
      "Gururu kırmamak için yanlışta ısrar etme.",
      "Her odaya merkez olarak girme.",
      "Cömertliği borç gibi sunma.",
    ],
    rituals: [
      "Bir dakika dur: omurganı dikleştir ve nefesini göğsünden geçir.",
      "Bugün paylaşacağın tek jesti içinden seç.",
      "Işığını zorlamadan, sakin bir nefesle topla.",
      "Gözlerini kapat, sahneden in, kalbe dön.",
      "Bir dakikalığına dur ve görünmenin yeterli olduğunu hatırla.",
      "Nefes: ısın, şişirme. Sadece dur.",
    ],
    rhythm: {
      sabah: ["Sabah görünürlüğünü seç: kim, ne, ne kadar.", "Güne ısınarak başla, sahneyi öğlene bırak."],
      ogle: ["Öğleden sonra tek bir işi parlat, hepsini ilan etme.", "Tepki gelmezse hacmi büyütme."],
      aksam: ["Akşam alkışı sayma; günü içten kapat.", "Sahneden in, bedene ve sessizliğe dön."],
    },
  },
  basak: {
    headlines: [
      "{name}: detayı seç, mükemmeli bırak",
      "{moon} altında {name} düzen kurar",
      "Bugün {name} için sade bir plan",
      "{name} işini ölçülü bitirsin",
      "{moon} · {name} net ve sakin",
      "{name}: faydalı olanı öne al",
    ],
    summaries: [
      "Başak gününde düzen işe yarar. Mükemmellik değil, tamamlanmış küçük iş.",
      "Gözün ayrıntıda. Bugün bir düzeltme yeter; bütün sistemi yeniden kurma.",
      "Hizmet etme isteğin yüksek. Yardımı seçerek ver, kendini tüketme.",
      "Zihin eleştiriye kayabilir. Onu işe, kişiye değil.",
      "Sadelik sende lüks. Fazlayı çıkar, özü bırak.",
      "Tempo kendi ölçünde kurulunca Başak rahatlar.",
    ],
    advice: [
      "Günü sade bir plana bağla ve bir maddeyi bitir.",
      "Bir detayı düzelt, on detayı aynı anda açma.",
      "Faydalı olanı seç; kusursuz olanı ertele.",
      "Listeni kısalt, sonra sırayla ilerle.",
      "Eleştirini işe çevir, kişiye çevirme.",
      "Küçük bir düzen, günü taşır.",
    ],
    avoid: [
      "Bitmiş bir işi ‘daha iyi olur’ diye yeniden açma.",
      "Kendine veya başkasına ince eleyip durma.",
      "Yardım ederken kontrolü ele alma.",
      "Sağlık veya düzen kaygısını günün merkezine koyma.",
      "Kusuru karakter sanma.",
      "Planı planlamakla günü tüketme.",
    ],
    rituals: [
      "Bir dakika dur: nefesini düzenle ve bugünün tek maddesini seç.",
      "Omuzlarını bırak, çeneni gevşet, listeden bir satır tut.",
      "Niyet: tamamlamak, mükemmelleştirmek değil.",
      "Kısa bir nefes halkası, sonra tek bir düzen hareketi.",
      "Zihindeki düzeltmeleri say, birini bırak.",
      "Bir dakikalığına dur ve ‘yeter’ noktasını koy.",
    ],
    rhythm: {
      sabah: ["Sabah tek bir maddeyle başla; listeyi şişirme.", "İlk saatlerde düzen kur, yeni sistem icat etme."],
      ogle: ["Öğleden sonra biten işi yeniden açma.", "Yardımı ölçülü tut; kendi işini de bırak."],
      aksam: ["Akşam hesabı kapat; yarının listesini şimdi yazma.", "Kusur avını bırak, günü yeterli say."],
    },
  },
  terazi: {
    headlines: [
      "{name}: dengeyi bir seçimle kur",
      "{moon} altında {name} zarif durur",
      "Bugün {name} için net bir orta",
      "{name} herkesi memnun etmesin",
      "{moon} · {name} ilişkiyi sadeleştirir",
      "{name}: güzeli seç, kararsızı bırak",
    ],
    summaries: [
      "Terazi gününde denge, her iki tarafı tutmak değil; birini net seçmektir.",
      "İlişki alanı öne çıkar. Uyum için kendini silme.",
      "Güzellik ve adalet aynı anda gelebilir. Kararsızlık ikisini de bozar.",
      "Karşıdakini okuma yeteneğin açık. Onu kendi kararının yerine koyma.",
      "Estetik bir dokunuş günü yumuşatır. Mükemmel denge arayışı yorar.",
      "Orta yol bazen bir ‘hayır’dır.",
    ],
    advice: [
      "İki seçenek varsa birini bugün netleştir.",
      "Uyum için gerçeği yumuşatma; kısaca söyle.",
      "İlişkide bir jest seç, üç telafi birden yapma.",
      "Kararını ertelemek yerine küçük bir tercih yap.",
      "Güzel olanı seç; herkesi dengelemeye çalışma.",
      "Sınırını zarifçe koy.",
    ],
    avoid: [
      "Herkesi memnun etmek için kendi yönünü kaybetme.",
      "Kararı karşı tarafa bırakıp sonra kırılma.",
      "Tartışmayı ‘uyum’ diye erteleme.",
      "Görünüşü denge sanma.",
      "İki kişi arasında çevirmen olup kendini yorma.",
      "Adaleti puan tablosuna çevirme.",
    ],
    rituals: [
      "Bir dakika dur: iki eli dengede tut, sonra birini seç.",
      "Nefesini eşit böl: alış, veriş. Sonra bir karar bırak.",
      "İçindeki ‘belki’yi bir cümleye indir.",
      "Zarif bir durak: kimle net, kimle mesafeli olduğunu seç.",
      "Gözlerini kapat, teraziyi bırak, yönü al.",
      "Bir dakikalığına dur ve uyumu kendi içinde kur.",
    ],
    rhythm: {
      sabah: ["Sabah tercihi erteleme; küçük bir evet veya hayır yeter.", "Güne ilişkiyi değil, kendi ritmini koy."],
      ogle: ["Öğleden sonra arabuluculuk yapma, net dur.", "Estetik bir düzenle işi yumuşat, kararı kaçırma."],
      aksam: ["Akşam hesabı eşitlemeye çalışma; günü bırak.", "Geceyi paylaşımla doldurmak zorunda değilsin."],
    },
  },
  akrep: {
    headlines: [
      "{name}: derine in, takılma",
      "{moon} altında {name} sessiz güçlenir",
      "Bugün {name} için seçilmiş bir sır",
      "{name} güveni ölçülü açsın",
      "{moon} · {name} dönüşümü tutar",
      "{name}: yoğunluğu yönet",
    ],
    summaries: [
      "Akrep gününde derinlik işe yarar. Her gölgeyi kazmak zorunda değilsin.",
      "Yoğunluk yüksek. Onu kontrol değil, seçilmiş bir alana ver.",
      "Güven meselesi öne çıkar. Test etme; net sor, net dinle.",
      "Dönüşüm hissi var. Eski bir sahneyi yeniden yaşamadan geç.",
      "Sezgin keskin. Kuşkuyu gerçek gibi büyütme.",
      "Sessizlik güç olabilir. Sessizliği ceza gibi kullanma.",
    ],
    advice: [
      "Bir konuyu derinleştir, beşini kazma.",
      "Güveni test etmek yerine açık bir cümle kur.",
      "Yoğunluğu tek bir işe veya kişiye bağla.",
      "Bırakman gerekeni adını koyarak bırak.",
      "Sezgine yer aç, senaryo yazma.",
      "Sırrını seçerek paylaş.",
    ],
    avoid: [
      "Kıskançlığı kanıt arayarak büyütme.",
      "Sessizliği ceza gibi kullanma.",
      "Geçmiş bir ihanet sahnesini bugüne yapıştırma.",
      "Kontrolü yakınlık sanma.",
      "Her ima için iç soruşturma açma.",
      "Yoğunluğu herkese yükleme.",
    ],
    rituals: [
      "Bir dakika dur: nefesini derinleştir ve tuttuğun şeyi bırak.",
      "Göğsündeki yoğunluğu say, sonra yumuşat.",
      "İçerideki soruyu sor, cevabı zorlama.",
      "Karanlıkta kalma; bir nefesle çık.",
      "Bir dakikalığına dur ve güven sınırını seç.",
      "Sessiz bir halka: dönüşüm, savaş değil.",
    ],
    rhythm: {
      sabah: ["Sabah yoğunluğu tek niyete bağla.", "İlk saatlerde eski hesabı açma."],
      ogle: ["Öğleden sonra ima etme; net sor.", "Güven testini işe karıştırma."],
      aksam: ["Akşam derine inebilirsin; takılı kalma.", "Geceyi kuşkuyla doldurma, bırakarak kapat."],
    },
  },
  yay: {
    headlines: [
      "{name}: ufku seç, kaçışı değil",
      "{moon} altında {name} açılır",
      "Bugün {name} için anlamlı bir adım",
      "{name} sözünü büyük tutmasın",
      "{moon} · {name} yönünü genişletir",
      "{name}: inancını ölçülü taşı",
    ],
    summaries: [
      "Yay gününde hareket ve anlam birlikte gelir. Kaçış ile yol aynı şey değildir.",
      "Ufuk açılır. Bugün bir yön seç; her kapıyı ‘özgürlük’ diye açma.",
      "Sözün büyüme eğilimindedir. Vaadi küçük tut, adımı gerçek tut.",
      "Öğrenme isteğin yüksek. Bir fikir yeter, manifesto gerekmez.",
      "Neşe bulaşıcı. Onu kaçışa çevirme.",
      "Yol hissi sende. Mesafe değil, anlam taşı.",
    ],
    advice: [
      "Bugün bir yön seç ve onu abartmadan ilerle.",
      "Büyük söz yerine küçük, gerçek bir adım at.",
      "Anlam arayışını tek bir soruya bağla.",
      "Ufkunu aç, kaçış planı kurma.",
      "Neşeni paylaş, ders vermeden.",
      "Yeni bir yere bak, eskiyi küçümsemeden.",
    ],
    avoid: [
      "Vaadi büyütüp günü boş bırakma.",
      "Doğruyu herkese anlatmak zorunda değilsin.",
      "Sıkılınca kapıyı çarpıp ‘özgürüm’ deme.",
      "Başkasının inancını hafife alma.",
      "Planı maceraya kurban etme.",
      "Kaçışı yolculuk sanma.",
    ],
    rituals: [
      "Bir dakika dur: nefesi genişlet ve bugünün yönünü seç.",
      "Omuzları aç, bakışı uzağa al, abartıyı bırak.",
      "İçinden bir niyet: yol, kaçış değil.",
      "Kısa bir durak, sonra tek anlamlı adım.",
      "Nefesle ufku içine al, sözü küçült.",
      "Bir dakikalığına dur ve inancını sakin tut.",
    ],
    rhythm: {
      sabah: ["Sabah yönünü seç; günü rastgele açma.", "İlk saatlerde büyük vaat verme."],
      ogle: ["Öğleden sonra bir öğrenme veya hareket yeter.", "Fikrini ders gibi sunma, paylaş."],
      aksam: ["Akşam yolculuğu zihinde bitir; kaçış kurma.", "Neşeyi uykuya yer bırakacak kadar tut."],
    },
  },
  oglak: {
    headlines: [
      "{name}: yapıyı kur, yükü büyütme",
      "{moon} altında {name} zamanı tutar",
      "Bugün {name} için ölçülü bir adım",
      "{name} sorumluluğu seçerek alsın",
      "{moon} · {name} kalıcı olanı öne alır",
      "{name}: hedefi sadeleştir",
    ],
    summaries: [
      "Oğlak gününde yapı işe yarar. Ağırlık değil; seçilmiş sorumluluk.",
      "Zaman sende netleşir. Uzun vadeyi bugünün tek adımına indir.",
      "Disiplin açık. Onu kendine ceza gibi kullanma.",
      "Görünür başarıdan çok kalıcı iz. Küçük, doğru iş yeter.",
      "Sınır koymak güçtür. Her yükü ‘ben hallederim’ diye alma.",
      "Ciddiyetin değerli. Soğuklukla karıştırma.",
    ],
    advice: [
      "Bir hedefi sadeleştir ve bugünkü adımını yaz.",
      "Sorumluluğu seçerek al, hepsini üstlenme.",
      "Yapıyı kur: saat, sıra, bitiş.",
      "Uzun vadeyi hatırla, bugünü ezme.",
      "Disiplini nazik tut.",
      "Kalıcı olanı öne al, vitrini değil.",
    ],
    avoid: [
      "İşini değerinin kanıtı yapma.",
      "Dinlenmeyi zayıflık sayma.",
      "Başkasının temposunu ‘ciddiyetsiz’ diye küçümseme.",
      "Kontrolü güvenlik sanıp her detayı tutma.",
      "Hedefi büyütüp adımı erteleme.",
      "Sertliği olgunluk sanma.",
    ],
    rituals: [
      "Bir dakika dur: omurganı hizala ve bugünün tek görevini seç.",
      "Nefesini ağır ve düzenli tut, yükü zihninden indir.",
      "Zamanı hisset: acele değil, süreklilik.",
      "Bir dakikalığına dur ve yeterlilik noktasını koy.",
      "Sessiz bir yapı: nefes, niyet, sınır.",
      "Omuzlardaki işi say, birini yarına bırak.",
    ],
    rhythm: {
      sabah: ["Sabah sırayı kur; günü kahramanlıkla açma.", "İlk iş en kalıcı olan olsun."],
      ogle: ["Öğleden sonra yeni yük alma, seçtiğini bitir.", "Toplantıyı uzatma; kararı yaz."],
      aksam: ["Akşam işi kapat; geceyi ofise çevirme.", "Başarıyı sayma, bedeni bırak."],
    },
  },
  kova: {
    headlines: [
      "{name}: yeni frekansı sakin tut",
      "{moon} altında {name} ayrı durur",
      "Bugün {name} için net bir fikir",
      "{name} farklılığını kanıtlamasın",
      "{moon} · {name} sistemi yumuşakça kaydırır",
      "{name}: mesafe değil, netlik",
    ],
    summaries: [
      "Kova gününde yeni bir frekans açılır. Farklı olmak, kopmak zorunda değildir.",
      "Zihin geleceğe kayar. Bugün bir fikri uygula, manifestoyu ertele.",
      "Mesafe koruyucu olabilir. Soğukluk gibi durmasın.",
      "Topluluk ve bağımsızlık aynı anda çekebilir. İkisini de abartma.",
      "Orijinalliğin açık. Onu şaşırtmak için kullanma.",
      "Sistemi görme yeteneğin var. Her şeyi birden değiştirmene gerek yok.",
    ],
    advice: [
      "Bir yeni fikri küçük uygula, hepsini ilan etme.",
      "Farklılığını kanıtlamadan dur.",
      "Mesafe koy, bağdan kopma.",
      "Toplulukta net ol, sahne kurma.",
      "Sistemi bir noktadan kaydır.",
      "Soğuk görünmemek için hissini bir cümlede söyle.",
    ],
    avoid: [
      "İnsanları ‘anlamıyor’ diye topluca eleme.",
      "Yeniliği üstünlük gibi sunma.",
      "Duyguyu gereksiz ilan etme.",
      "Bağımsızlık adına sözünü geciktirme.",
      "Her kuralı kırmak zorunda değilsin.",
      "Fikrini soğuk bir duvar gibi tutma.",
    ],
    rituals: [
      "Bir dakika dur: zihindeki statik gürültüyü bırak, bir frekans seç.",
      "Nefesi nötr tut: ne ısın, ne kaç.",
      "Yeni fikri içeride tut, şişirme.",
      "Bir dakikalığına dur ve bağ ile mesafeyi ayır.",
      "Sessiz bir halka: netlik, soğukluk değil.",
      "Alnını gevşet, geleceği bugüne indirme.",
    ],
    rhythm: {
      sabah: ["Sabah fikri not et, hemen yayınlama.", "Güne sistem kurarak değil, bir netlikle başla."],
      ogle: ["Öğleden sonra gruba katıl, kopma.", "Yeniliği toplantının konusu yapma; bir deneme yeter."],
      aksam: ["Akşam zihni kapat; geleceği geceye taşıma.", "Mesafe ihtiyacını uykuya çevir."],
    },
  },
  balik: {
    headlines: [
      "{name}: akışı tut, kaybolma",
      "{moon} altında {name} sezgi açılır",
      "Bugün {name} için yumuşak bir sınır",
      "{name} rüyayı güne karıştırmasın",
      "{moon} · {name} içeriği süzgeçler",
      "{name}: şefkati ölçülü tut",
    ],
    summaries: [
      "Balık gününde sınırlar incelir. Şefkat işe yarar; erimek zorunda değilsin.",
      "Sezgi yüksek. Onu gerçek gibi büyütmeden dinle.",
      "Başkasının hissi kolay geçer. Süzgeç koy, kapanma.",
      "Hayal ve yorgunluk karışabilir. Küçük bir gerçek iş, günü tutar.",
      "Bağışlama isteğin açık. Kendini silerek bağışlama.",
      "Su gibi ak. Yatağını da seç.",
    ],
    advice: [
      "Sezgine kısa bir alan aç, sonra somut bir iş seç.",
      "Şefkati ver, sınırını da koy.",
      "Rüyayı not et, günü ona teslim etme.",
      "Bir yumuşak jest yeter; her yarayı alma.",
      "Akışı tut, kaybolmayı bırak.",
      "İç sesini dinle, her imayı kader sanma.",
    ],
    avoid: [
      "Başkasının duygusunu kendi yükün yapma.",
      "Kaçışı uyku, hayal veya belirsizlikle büyütme.",
      "Sınırı ‘kötülük’ gibi görme.",
      "Her acıya açık kapı bırakma.",
      "Gerçeği sisle örtme.",
      "Fedakârlığı kimlik yapma.",
    ],
    rituals: [
      "Bir dakika dur: nefesi su gibi geçir, sonra kıyıya çık.",
      "Gözlerini yum, dalgayı izle, kaybolma.",
      "Şefkati kendine bir nefesle çevir.",
      "Sınırı yumuşakça çiz: burada duruyorum.",
      "Bir dakikalığına dur ve sisin içinden bir netlik al.",
      "Yumuşak halka: ak, dağılma.",
    ],
    rhythm: {
      sabah: ["Sabah sis dağılmadan büyük karar verme.", "Güne yumuşak başla, yatağını da seç."],
      ogle: ["Öğleden sonra başkasının havasını alma; kısa ara ver.", "Hayali işe karıştırma, bir somut adım at."],
      aksam: ["Akşam rüyaya yer aç; günü yeniden yaşama.", "Şefkati geceye taşıma, uykuya bırak."],
    },
  },
};

export function fillDailyCopy(template: string, name: string, moon: string) {
  return template.replaceAll("{name}", name).replaceAll("{moon}", moon);
}
